import type { CSSProperties } from "react";

import { tayoriPhotoFrameStyles } from "./tayoriPhotoFrameStyles";

export const deliveredLetterStyles = {
  sheet: {
    position: "relative",
    width: "100%",
    display: "grid",
    justifyItems: "center",
    gap: "10px",
    padding: "0 10px",
    boxSizing: "border-box",
    border: "none",
    borderRadius: 0,
    background: "transparent",
    boxShadow: "none",
  },
  masthead: {
    width: "100%",
    minHeight: "30px",
    display: "grid",
    justifyItems: "center",
    alignContent: "center",
    gap: "5px",
    paddingTop: "1px",
    boxSizing: "border-box",
  },
  title: {
    margin: 0,
    color: "var(--ink, #292721)",
    fontFamily: "var(--font-display)",
    fontSize: "22px",
    fontWeight: 500,
    lineHeight: 1.35,
    letterSpacing: 0,
  },
  mastheadRule: {
    width: "32px",
    height: "1px",
    borderRadius: "999px",
    background: "var(--line-strong, #cfc7b9)",
    opacity: 0.72,
  },
  photoFrame: {
    ...tayoriPhotoFrameStyles.frame,
    position: "relative",
    aspectRatio: "1 / 1",
    width: "100%",
    padding: 0,
    boxSizing: "border-box",
    overflow: "hidden",
  },
  photo: {
    ...tayoriPhotoFrameStyles.image,
    width: "100%",
    height: "100%",
    objectFit: "contain",
    background: "var(--paper-card, #f1efe9)",
  },
  loadingOverlay: {
    position: "absolute",
    inset: 0,
    zIndex: 2,
    display: "grid",
    placeItems: "center",
    margin: 0,
    padding: "16px",
    boxSizing: "border-box",
    borderRadius: 0,
    background:
      "color-mix(in srgb, var(--paper-card, #fffaf2) 86%, transparent)",
    color: "var(--ink-soft, #746a5f)",
    fontFamily: "var(--font-ui)",
    fontSize: "13px",
    fontWeight: 400,
    lineHeight: 1.6,
    letterSpacing: 0,
    textAlign: "center",
    pointerEvents: "none",
  },
  note: {
    width: "100%",
    margin: 0,
    padding: "2px 6px 0",
    boxSizing: "border-box",
    color: "var(--ink-soft, #746a5f)",
    fontFamily: "var(--font-ui)",
    fontSize: "13.5px",
    fontWeight: 400,
    lineHeight: 1.65,
    letterSpacing: 0,
    textAlign: "center",
  },
  savedPhrase: {
    whiteSpace: "nowrap",
  },
  action: {
    width: "min(280px, 100%)",
    minHeight: "54px",
    marginTop: "2px",
    border:
      "1px solid color-mix(in srgb, var(--line, #b9ad9d) 42%, transparent)",
    borderRadius: "var(--radius-full, 999px)",
    background:
      "linear-gradient(180deg, color-mix(in srgb, var(--paper-card, #fffaf2) 98%, white 2%), color-mix(in srgb, var(--paper-warm, #f4eee3) 88%, white 12%))",
    color: "var(--ink, #292721)",
    fontFamily: "var(--font-ui)",
    fontSize: "15px",
    fontWeight: 520,
    lineHeight: 1.35,
    letterSpacing: "0.02em",
    cursor: "pointer",
    boxShadow:
      "inset 0 1px 0 rgba(255,255,255,0.72), 0 12px 24px -20px rgba(80,66,50,0.32)",
    WebkitTapHighlightColor: "transparent",
  },
  recoveryPanel: {
    width: "min(100%, 330px)",
    display: "grid",
    justifyItems: "center",
    gap: "8px",
    padding: "11px 14px",
    boxSizing: "border-box",
    border:
      "1px solid color-mix(in srgb, var(--seal, #a8584e) 22%, transparent)",
    borderRadius: "10px",
    background:
      "color-mix(in srgb, var(--paper-card, #fffaf2) 78%, transparent)",
  },
  recoveryText: {
    margin: 0,
    color: "var(--ink-soft, #746a5f)",
    fontFamily: "var(--font-ui)",
    fontSize: "13px",
    fontWeight: 400,
    lineHeight: 1.65,
    letterSpacing: 0,
    textAlign: "center",
  },
} satisfies Record<string, CSSProperties>;
